[GLOBAL]
pants_version = "2.11.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.awslambda.python",
]

[python]
interpreter_constraints = ["CPython==3.9.*"]
enable_resolves = true

[anonymous-telemetry]
enabled = false

