[GLOBAL]
pants_version = "2.10.1rc0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.awslambda.python",
]

use_deprecated_python_macros = false

[python]
interpreter_constraints = ["CPython==3.9.*"]
enable_resolves = true

[anonymous-telemetry]
enabled = false

